In [1]:
from google.colab import drive 
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [2]:
!pip install pydot --quiet
!pip install gensim==3.8.3 --quiet
!pip install tensorflow-datasets --quiet
!pip install -U tensorflow-text==2.8.2 --quiet
!pip install transformers --quiet

     |████████████████████████████████| 24.2 MB 70.0 MB/s 
     |████████████████████████████████| 4.9 MB 15.5 MB/s 
     |████████████████████████████████| 498.0 MB 11 kB/s 
     |████████████████████████████████| 1.4 MB 66.9 MB/s 
     |████████████████████████████████| 5.8 MB 45.6 MB/s 
     |████████████████████████████████| 462 kB 77.4 MB/s 
     |████████████████████████████████| 5.8 MB 14.8 MB/s 
     |████████████████████████████████| 182 kB 80.1 MB/s 
     |████████████████████████████████| 7.6 MB 58.8 MB/s 


In [3]:
import pandas as pd
import numpy as np
import sys
import os
import re

import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.layers import Embedding, Input, Dense, Lambda
from tensorflow.keras.models import Model
import tensorflow.keras.backend as K
import tensorflow_datasets as tfds
import tensorflow_text as tf_text

from transformers import BertTokenizer, TFBertModel


import sklearn as sk

import nltk
from nltk.data import find

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


#This continues to work with gensim 3.8.3.  It doesn't yet work with 4.x.  
#Make sure your pip install command specifies gensim==3.8.3
import gensim
from gensim.models import word2vec, FastText
from gensim.utils import tokenize

In [4]:
os.chdir('/content/gdrive/MyDrive/Windows/')

In [5]:
df=pd.read_csv('Windows_log_labeled.csv')

In [6]:
df.head()

Unnamed: 0  LineId       Date     Time  Type Admin  \
0           0       1  9/27/2016  4:30:30  Info   CBS   
1           1       2  9/28/2016  4:30:30  Info   CBS   
2           2       3  9/28/2016  4:30:31  Info   CSI   
3           3       4  9/28/2016  4:30:31  Info   CSI   
4           4       5  9/28/2016  4:30:31  Info   CSI   

                                             Content   EventId  \
0          Starting TrustedInstaller initialization.  4351fc0e   
1  Loaded Servicing Stack v6.1.7601.23505 with Co...  b642288b   
2  00000001@2016/9/27:20:30:31.455 WcpInitialize ...  a742c417   
3  00000002@2016/9/27:20:30:31.458 WcpInitialize ...  a742c417   
4  00000003@2016/9/27:20:30:31.458 WcpInitialize ...  a742c417   

                                       EventTemplate  Label  
0                           <*> TrustedInstaller <*>      0  
1  Loaded Servicing Stack v<*> with Core: C:\Wind...      0  
2  <*>@<*>/<*>/<*>:<*>:<*>:<*>.<*> WcpInitialize ...      0  
3  <*>@<*>/<*>/<*>:<*>:<*>:<*>.<*> WcpInitialize ...      0  
4  <*>@<*>/<*>/<*>:<*>:<*>:<*>.<*> WcpInitialize ...      0

In [7]:
nltk.download('word2vec_sample')

word2vec_sample = str(find('models/word2vec_sample/pruned.word2vec.txt'))

model = gensim.models.KeyedVectors.load_word2vec_format(word2vec_sample, binary=False)

[nltk_data] Downloading package word2vec_sample to /root/nltk_data...
[nltk_data]   Unzipping models/word2vec_sample.zip.


In [8]:
whole_data_emb = df["Content"].values.tolist()
whole_data_label=df["Label"].values.tolist()

In [9]:
len(whole_data_emb)

79966

In [10]:
# from sklearn.model_selection import train_test_split
# X_train, X_val, y_train, y_val = train_test_split(whole_data_emb, whole_data_label, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [11]:
train_ratio = 0.80
test_ratio = 0.10
validation_ratio = 0.10



X_train, X_test, y_train, y_test = train_test_split(whole_data_emb, whole_data_label, test_size=test_ratio, random_state=1)

X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=validation_ratio/(train_ratio+test_ratio))

print("Train Size:",len(X_train))
print("Test Size:",len(X_test))
print("Valid Size:",len(X_valid))

Train Size: 63972
Test Size: 7997
Valid Size: 7997


In [12]:
#@title Embedding Matrix Creation

EMBEDDING_DIM = 300    # we know... it's 300

# initialize embedding matrix and word-to-id map:
embedding_matrix = np.zeros((len(model.vocab.keys()) + 1, EMBEDDING_DIM))       
vocab_dict = {}

# build the embedding matrix and the word-to-id map:
for i, word in enumerate(model.vocab.keys()):
    embedding_vector = model[word]
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector
        vocab_dict[word] = i

# we can use the last index at the end of the vocab for unknown tokens
vocab_dict['[UNK]'] = len(vocab_dict)

In [13]:
SEQUENCE_LENGTH = 100

In [14]:
def docs_to_vocab_ids(tokenized_texts_list):
    """
    converting a list of strings to a list of lists of word ids
    """
    texts_vocab_ids = []
    text_labels = []
    valid_example_list = []
    for i, token_list in enumerate(tokenized_texts_list):

        # Get the vocab id for each token in this doc ([UNK] if not in vocab)
        vocab_ids = []
        for token in list(token_list.numpy()):
            decoded = token.decode('utf-8', errors='ignore')
            if decoded in vocab_dict:
                vocab_ids.append(vocab_dict[decoded])
            else:
                vocab_ids.append(vocab_dict['[UNK]'])
            
        # Truncate text to max length, add padding up to max length
        vocab_ids = vocab_ids[:SEQUENCE_LENGTH]
        n_padding = (SEQUENCE_LENGTH - len(vocab_ids))
        # For simplicity in this model, we'll just pad with unknown tokens
        vocab_ids += [vocab_dict['[UNK]']] * n_padding
        valid_example_list.append(i)
        # Add this example to the list of converted docs
        texts_vocab_ids.append(vocab_ids)
            
        if i % 5000 == 0:
            print('Examples processed: ', i)

    print('Total examples: ', i)
    return (np.array(texts_vocab_ids), valid_example_list)

In [15]:
X_train=np.array(X_train)
X_test=np.array(X_test)

In [16]:
X_train.shape

(63972,)

In [17]:
X_test.shape

(7997,)

In [18]:
tokenizer = tf_text.WhitespaceTokenizer()
train_tokens = tokenizer.tokenize(X_train[:500000])
test_tokens= tokenizer.tokenize(X_test[:150000])                          

In [19]:
ytrain=np.array(y_train[:500000])
ytest=np.array(y_test[:150000])

In [20]:
train_tokens[0:3]

<tf.RaggedTensor [[b'Read', b'out', b'cached', b'package', b'applicability', b'for',
  b'package:', b'Package_for_KB3092627~31bf3856ad364e35~amd64~~6.1.1.0,',
  b'ApplicableState:', b'112,', b'CurrentState:112']                     ,
 [b'Expecting', b'attribute', b'name', b'[HRESULT', b'=', b'0x800f080d',
  b'-', b'CBS_E_MANIFEST_INVALID_ITEM]']                                ,
 [b'Applicability(ComponentAnalyzerEvaluateSelfUpdate):', b'Component:',
  b'x86_microsoft-windows-m..ditevtlog.resources_31bf3856ad364e35_6.1.7601.23126_he-il_43301ec8aaaab8b5,',
  b'elevate:', b'2,', b'applicable(true/false):', b'0']                                                   ]>

In [21]:
test_tokens[0:3]

<tf.RaggedTensor [[b'Appl:', b'Selfupdate,', b'Component:',
  b'x86_microsoft-windows-m..ditevtlog.resources_31bf3856ad364e35_0.0.0.0_es-es_7daaf684a22d94a8',
  b'(6.1.7601.23126),', b'elevation:2,', b'lower', b'version', b'revision',
  b'holder:', b'0.0.0.0']                                                                         ,
 [b'Appl:', b'detect', b'Parent,', b'Package:',
  b'Package_for_KB3060716~31bf3856ad364e35~amd64~~6.1.1.0,', b'Parent:',
  b'Microsoft-Windows-WinPE-LanguagePack-Package~31bf3856ad364e35~amd64~bg-BG~6.1.7601.17514,',
  b'Disposition', b'=', b'Detect,', b'VersionComp:', b'EQ,',
  b'ServiceComp:', b'EQ,', b'BuildComp:', b'EQ,', b'DistributionComp:',
  b'GE,', b'RevisionComp:', b'GE,', b'Exist:', b'present']                                     ,
 [b'Appl:', b'Selfupdate,', b'Component:',
  b'amd64_netfx35linq-system.web.extensions_31bf3856ad364e35_0.0.0.0_none_4e723abaebb210fc',
  b'(6.1.7601.21884),', b'elevation:2,', b'lower', b'version', b'revision',
  b'ho

In [22]:
train_input_ids, train_valid_example_list = docs_to_vocab_ids(train_tokens)
test_input_ids, test_valid_example_list = docs_to_vocab_ids(test_tokens)

Examples processed:  0
Examples processed:  5000
Examples processed:  10000
Examples processed:  15000
Examples processed:  20000
Examples processed:  25000
Examples processed:  30000
Examples processed:  35000
Examples processed:  40000
Examples processed:  45000
Examples processed:  50000
Examples processed:  55000
Examples processed:  60000
Total examples:  63971
Examples processed:  0
Examples processed:  5000
Total examples:  7996


In [23]:
train_input_ids[:2]

array([[ 1362, 10490, 43981, 23226, 19052, 11511, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981],
       [ 2319, 25475, 10804, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 4398

In [24]:
test_input_ids[:2]

array([[43981, 43981, 43981, 43981, 43981, 43981, 21120,  9626,  2072,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981],
       [43981, 20307, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981, 43981,
        43981, 43981, 43981, 32772, 43981, 43981, 43981, 4398

In [25]:
from sklearn.metrics import confusion_matrix
def conf_matrix(model,xtest1,ytest1):
  y_pred = model.predict(xtest1)
  y_pred = np.argmax(y_pred, axis=1)
  conf_mat = confusion_matrix(ytest1, y_pred)
  TP=conf_mat[0][0]
  FP=conf_mat[0][1]
  FN=conf_mat[1][0]
  TN=conf_mat[1][1]
  recall=TP*100/(TP+FN)
  print('Recall:',recall)
  F1_score=(2*TP*100)/(2*TP+FP+FN)
  print('F1 Score:',F1_score)

  return recall, F1_score, conf_mat

In [26]:
def create_dan_model(retrain_embeddings=False, 
                     max_sequence_length=SEQUENCE_LENGTH,
                     hidden_dim=100,
                     dropout=0.3,
                     embedding_initializer='word2vec', 
                     learning_rate=0.001):
  """
  Construct the DAN model including the compilation and return it. Parametrize it using the arguments.
  :param retrain_embeddings: boolean, indicating whether  the word embeddings are trainable
  :param hidden_dim: dimension of the hidden layer
  :param dropout: dropout applied to the hidden layer

  :returns: the compiled model
  """

  if embedding_initializer == 'word2vec':
    embeddings_initializer=tf.keras.initializers.Constant(embedding_matrix)
  else:
    embeddings_initializer='uniform'

  dan_input_layer = tf.keras.layers.Input(shape=(max_sequence_length,), dtype='int64')
  
  dan_embedding_layer = Embedding(embedding_matrix.shape[0],
                                    embedding_matrix.shape[1],
                                    embeddings_initializer=tf.keras.initializers.Constant(embedding_matrix),
                                    input_length=SEQUENCE_LENGTH,
                                    trainable=retrain_embeddings)
  
  dan_embeddings = dan_embedding_layer(dan_input_layer)
    
  dan_avg_embeddings = tf.keras.layers.Lambda(lambda x: K.mean(x, axis=1),name='averaging')(dan_embeddings)
  
  last_hidden_output = tf.keras.layers.Dense(100, activation='relu',
                                                   name='dan_hidden_%d' % i)(dan_avg_embeddings)

  last_hidden_output = tf.keras.layers.Dropout(dropout)(last_hidden_output)

  dan_classification = tf.keras.layers.Dense(1,
                                               activation='sigmoid',
                                               name='dan_classification')(last_hidden_output)

    
  dan_model1 = tf.keras.models.Model(inputs=dan_input_layer, outputs=dan_classification)
    
    
  dan_model1.compile(loss='binary_crossentropy',
                      optimizer=tf.keras.optimizers.Adam(learning_rate=0.001,
                                                         beta_1=0.9,
                                                         beta_2=0.999,
                                                         epsilon=1e-07,
                                                         amsgrad=False,
                                                         name='Adam'),
                      metrics='accuracy')
  
  print(dan_model1.summary())
  return dan_model1


In [27]:
dan_model1 = create_dan_model()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 100)]             0         
                                                                 
 embedding (Embedding)       (None, 100, 300)          13194600  
                                                                 
 averaging (Lambda)          (None, 300)               0         
                                                                 
 dan_hidden_43980 (Dense)    (None, 100)               30100     
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dan_classification (Dense)  (None, 1)                 101       
                                                                 
Total params: 13,224,801
Trainable params: 30,201
Non-trainab

In [28]:

history_noshuffle = dan_model1.fit(train_input_ids,
                            ytrain,
                            validation_data=(test_input_ids,ytest),
                            batch_size=32,
                            epochs=5,
                            shuffle=True
                            )

Epoch 1/5
2000/2000 [==============================] - 9s 3ms/step - loss: 0.1186 - accuracy: 0.9634 - val_loss: 0.0270 - val_accuracy: 0.9972
Epoch 2/5
2000/2000 [==============================] - 6s 3ms/step - loss: 0.0242 - accuracy: 0.9966 - val_loss: 0.0086 - val_accuracy: 0.9972
Epoch 3/5
2000/2000 [==============================] - 6s 3ms/step - loss: 0.0123 - accuracy: 0.9984 - val_loss: 0.0031 - val_accuracy: 0.9999
Epoch 4/5
2000/2000 [==============================] - 6s 3ms/step - loss: 0.0064 - accuracy: 0.9995 - val_loss: 0.0015 - val_accuracy: 1.0000
Epoch 5/5
2000/2000 [==============================] - 6s 3ms/step - loss: 0.0040 - accuracy: 0.9997 - val_loss: 7.9678e-04 - val_accuracy: 1.0000


In [29]:
conf_matrix(dan_model1,test_input_ids,ytest)

Recall: 93.08490684006503
F1 Score: 96.41862573667508


(93.08490684006503, 96.41862573667508, array([[7444,    0],
        [ 553,    0]]))

In [30]:
def create_wan_model(retrain_embeddings=False, 
                     max_sequence_length=SEQUENCE_LENGTH,
                     hidden_dim=100,
                     dropout=0.3,
                     learning_rate=0.001):
  """
  Construct the WAN model including the compilation and return it. Parametrize it using the arguments.
  :param retrain_embeddings: boolean, indicating whether the word embeddings are trainable
  :param hidden_dim: dimension of the hidden layer
  :param dropout: dropout applied to the hidden layer

  :returns: the compiled model
  """
  ### YOUR CODE HERE

  #if embedding_initializer == 'word2vec':
      #embeddings_initializer=tf.keras.initializers.Constant(embedding_matrix)
  #else:
      #embeddings_initializer='uniform'

  wan_input_layer = tf.keras.layers.Input(shape=(max_sequence_length,), dtype='int64') #fake input layer
 

  wan_embedding_layer = Embedding(embedding_matrix.shape[0],
                                    embedding_matrix.shape[1],
                                    embeddings_initializer=tf.keras.initializers.Constant(embedding_matrix),
                                    input_length=SEQUENCE_LENGTH,
                                    trainable=retrain_embeddings)
  
  
  wan_embeddings = wan_embedding_layer(wan_input_layer)
  
  #query
  wan_query_layer = tf.keras.layers.Dense(embedding_matrix.shape[1]) #query
  
  wan_one_vector = tf.Variable(tf.ones((1, 1, 1)))
  
  wan_batch_of_ones = tf.tile(wan_one_vector, (tf.shape(wan_input_layer)[0], 1, 1)) 

  wan_query_vector = wan_query_layer(wan_batch_of_ones)

    
  wan_avg_embeddings = tf.keras.layers.Lambda(lambda x: K.mean(x, axis=1),name='averaging')(wan_embeddings)

  wan_attention_output,wan_attention_weights= tf.keras.layers.Attention()([wan_query_vector,wan_embeddings],return_attention_scores=True)

  
  wan_attention_output = tf.keras.layers.Reshape((wan_attention_output.shape[-1],))(wan_attention_output)


  
  last_hidden_output = tf.keras.layers.Dense(100, activation='relu',
                                                   name='wan_hidden_%d' % i)(wan_attention_output)

  last_hidden_output = tf.keras.layers.Dropout(dropout)(last_hidden_output)

  wan_classification = tf.keras.layers.Dense(1,
                                               activation='sigmoid',
                                               name='classification')(last_hidden_output)

    
  wan_model1 = tf.keras.models.Model(inputs=wan_input_layer, outputs=[wan_classification,wan_attention_weights])
    
    
  wan_model1.compile(loss=['binary_crossentropy',None],
                      optimizer=tf.keras.optimizers.Adam(learning_rate=0.001,
                                                         beta_1=0.9,
                                                         beta_2=0.999,
                                                         epsilon=1e-07,
                                                         amsgrad=False,
                                                         name='Adam'),
                      metrics='accuracy')
  
  print(wan_model1.summary())
  
  return wan_model1


In [31]:

wan_model = create_wan_model()
history_wan = wan_model.fit(train_input_ids,
                            ytrain,
                            validation_data=(test_input_ids,ytest),
                            batch_size=32,
                            epochs=10,
                            shuffle=True
                            )
# use wan_history = ... below

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 100)]        0           []                               
                                                                                                  
 tf.compat.v1.shape (TFOpLambda  (2,)                0           ['input_2[0][0]']                
 )                                                                                                
                                                                                                  
 tf.__operators__.getitem (Slic  ()                  0           ['tf.compat.v1.shape[0][0]']     
 ingOpLambda)                                                                                     
                                                                                            

In [32]:
conf_matrix(wan_model,test_input_ids,ytest)

/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


ValueError: ignored

In [33]:
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [34]:
bert_model = TFBertModel.from_pretrained('bert-base-cased')

Downloading:   0%|          | 0.00/527M [00:00<?, ?B/s]

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [38]:
df1=pd.read_csv('Windows_log_labeled.csv')

In [39]:
df1.head()

Unnamed: 0  LineId       Date     Time  Type Admin  \
0           0       1  9/27/2016  4:30:30  Info   CBS   
1           1       2  9/28/2016  4:30:30  Info   CBS   
2           2       3  9/28/2016  4:30:31  Info   CSI   
3           3       4  9/28/2016  4:30:31  Info   CSI   
4           4       5  9/28/2016  4:30:31  Info   CSI   

                                             Content   EventId  \
0          Starting TrustedInstaller initialization.  4351fc0e   
1  Loaded Servicing Stack v6.1.7601.23505 with Co...  b642288b   
2  00000001@2016/9/27:20:30:31.455 WcpInitialize ...  a742c417   
3  00000002@2016/9/27:20:30:31.458 WcpInitialize ...  a742c417   
4  00000003@2016/9/27:20:30:31.458 WcpInitialize ...  a742c417   

                                       EventTemplate  Label  
0                           <*> TrustedInstaller <*>      0  
1  Loaded Servicing Stack v<*> with Core: C:\Wind...      0  
2  <*>@<*>/<*>/<*>:<*>:<*>:<*>.<*> WcpInitialize ...      0  
3  <*>@<*>/<*>/<*>:<*>:<*>:<*>.<*> WcpInitialize ...      0  
4  <*>@<*>/<*>/<*>:<*>:<*>:<*>.<*> WcpInitialize ...      0

In [41]:
whole_data_emb = df1["Content"].values.tolist()
whole_data_label=df1["Label"].values.tolist()

In [42]:
train_ratio = 0.80
test_ratio = 0.10
validation_ratio = 0.10



X_train, X_test, y_train, y_test = train_test_split(whole_data_emb, whole_data_label, test_size=test_ratio, random_state=1)

X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=validation_ratio/(train_ratio+test_ratio))

print("Train Size:",len(X_train))
print("Test Size:",len(X_test))
print("Valid Size:",len(X_valid))

Train Size: 63972
Test Size: 7997
Valid Size: 7997


In [43]:

# num_train_examples = len(X_train)*.1
# num_test_examples = len(X_test)*.1
# num_val_examples=len(X_valid)*.1
# max_length = 50

In [44]:
# #num_train_examples = 250000
# num_train_examples = 50000
# num_test_examples = 20000
# num_val_examples=20000
max_length = 50


# x_train = bert_tokenizer(X_train[:num_train_examples], 
#               max_length=max_length,
#               truncation=True,
#               padding='max_length', 
#               return_tensors='tf')

# x_test = bert_tokenizer(X_test[:num_test_examples], 
#               max_length=max_length,
#               truncation=True,
#               padding='max_length', 
#               return_tensors='tf')

# x_val= bert_tokenizer(X_valid[:num_val_examples], 
#               max_length=max_length,
#               truncation=True,
#               padding='max_length', 
#               return_tensors='tf')

x_train = bert_tokenizer(X_train, 
              max_length=max_length,
              truncation=True,
              padding='max_length', 
              return_tensors='tf')

x_test = bert_tokenizer(X_test, 
              max_length=max_length,
              truncation=True,
              padding='max_length', 
              return_tensors='tf')

x_val= bert_tokenizer(X_valid, 
              max_length=max_length,
              truncation=True,
              padding='max_length', 
              return_tensors='tf')





def select_min_length_examples(x_data, y_data):

  x_input_ids = []
  y_labels = []

  for ((input_ids, masks), label) in zip(zip(x_data['input_ids'], x_data['attention_mask']), y_data):
    if masks[-1] == 1:
      x_input_ids.append(input_ids)
      y_labels.append(label)

  return np.array(x_input_ids), np.array(y_labels) 


In [45]:
# y_train = y_train[:num_train_examples]
# y_test = y_train[:num_train_examples]
# y_val = y_train[:num_val_examples]
y_train = y_train
y_test = y_test
y_val = y_valid

In [46]:
x_train

{'input_ids': <tf.Tensor: shape=(63972, 50), dtype=int32, numpy=
array([[  101,   138,  8661, ...,   119,   121,   102],
       [  101,   138,  8661, ...,   121,   119,   102],
       [  101,   138,  8661, ...,  1955,  1830,   102],
       ...,
       [  101,   138,  8661, ...,  1955,  1830,   102],
       [  101, 18012,   131, ...,     0,     0,     0],
       [  101, 15152,  1149, ...,   121,   117,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(63972, 50), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(63972, 50), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]], dtype=in

In [47]:
x_val

{'input_ids': <tf.Tensor: shape=(7997, 50), dtype=int32, numpy=
array([[  101, 15152,  1149, ...,   119,   123,   102],
       [  101, 16409, 26426, ...,     0,     0,     0],
       [  101,   138,  8661, ...,  1955,  1830,   102],
       ...,
       [  101, 15152,  1149, ...,   121,   117,   102],
       [  101,   138,  8661, ...,   119,   121,   102],
       [  101,  9734,  7535, ...,   119,   121,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(7997, 50), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(7997, 50), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32

In [48]:
bert_train_input_ids, bert_train_labels = select_min_length_examples(x_train, y_train)
bert_test_input_ids, bert_test_labels = select_min_length_examples(x_test, y_test)
bert_val_input_ids, bert_val_labels = select_min_length_examples(x_val, y_val)

In [49]:
SEQUENCE_LENGTH = 50

In [50]:
def create_bert_cls_model(hidden_size = 100, 
                          dropout=0.3,
                          learning_rate=0.0005):
    """
    Build a simple classification model with BERT. Use the CLS Token output for classification purposes.
    """


    

    ### YOUR CODE HERE
    input_ids = tf.keras.layers.Input(shape=(SEQUENCE_LENGTH,), dtype=tf.int64, name='input_ids_layer')
    #token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='token_type_ids_layer')
    #attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='attention_mask_layer')

    
    bert_inputs = {'input_ids': input_ids}  

 

    bert_out = bert_model(bert_inputs)

    pooled_token = bert_out[1]
    #cls_token = bert_out[0][:, 0, :]

    hidden = tf.keras.layers.Dense(hidden_size, activation='relu', name='hidden_layer')(pooled_token)


    hidden = tf.keras.layers.Dropout(dropout)(hidden)  

    classification = tf.keras.layers.Dense(1, activation='sigmoid',name='classification_layer')(hidden)
    
    classification_model = tf.keras.Model(inputs=[input_ids], outputs=[classification])
    
    classification_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                                 loss=tf.keras.losses.BinaryCrossentropy(from_logits=False), 
                                 metrics='accuracy')


    ### END YOUR CODE
    print(classification_model.summary())
    return classification_model

In [51]:
bert_classification_model = create_bert_cls_model()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_ids_layer (InputLayer  [(None, 50)]             0         
 )                                                               
                                                                 
 tf_bert_model (TFBertModel)  TFBaseModelOutputWithPoo  108310272
                             lingAndCrossAttentions(l            
                             ast_hidden_state=(None,             
                             50, 768),                           
                              pooler_output=(None, 76            
                             8),                                 
                              past_key_values=None, h            
                             idden_states=None, atten            
                             tions=None, cross_attent            
                             ions=None)                    

In [52]:
b_model = create_bert_cls_model()
history_wan = b_model.fit(bert_train_input_ids,
                            bert_train_labels,
                            validation_data=(bert_val_input_ids,bert_val_labels),
                            batch_size=8,
                            epochs=2
                            )

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_ids_layer (InputLayer  [(None, 50)]             0         
 )                                                               
                                                                 
 tf_bert_model (TFBertModel)  TFBaseModelOutputWithPoo  108310272
                             lingAndCrossAttentions(l            
                             ast_hidden_state=(None,             
                             50, 768),                           
                              pooler_output=(None, 76            
                             8),                                 
                              past_key_values=None, h            
                             idden_states=None, atten            
                             tions=None, cross_attent            
                             ions=None)                    

In [53]:
conf_matrix(b_model,bert_val_input_ids,bert_val_labels)

Recall: 99.93664871713652
F1 Score: 99.96831432192648


(99.93664871713652, 99.96831432192648, array([[6310,    0],
        [   4,    0]]))

In [54]:
def create_bert_cls_model1(hidden_size = 100, 
                          dropout=0.3,
                          learning_rate=0.0005):
    """
    Build a simple classification model with BERT. Use the CLS Token output for classification purposes.
    """


    

    ### YOUR CODE HERE
    input_ids = tf.keras.layers.Input(shape=(SEQUENCE_LENGTH,), dtype=tf.int64, name='input_ids_layer')
    #token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='token_type_ids_layer')
    #attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='attention_mask_layer')

    
    bert_inputs = {'input_ids': input_ids}  

 

    bert_out = bert_model(bert_inputs)

    #pooled_token = bert_out[1]
    cls_token = bert_out[0][:, 0, :]

    hidden = tf.keras.layers.Dense(hidden_size, activation='relu', name='hidden_layer')(cls_token)


    hidden = tf.keras.layers.Dropout(dropout)(hidden)  

    classification = tf.keras.layers.Dense(1, activation='sigmoid',name='classification_layer')(hidden)
    
    classification_model = tf.keras.Model(inputs=[input_ids], outputs=[classification])
    
    classification_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                                 loss=tf.keras.losses.BinaryCrossentropy(from_logits=False), 
                                 metrics='accuracy')


    ### END YOUR CODE
    print(classification_model.summary())
    return classification_model

In [55]:
bert_classification_model1 = create_bert_cls_model1()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_ids_layer (InputLayer  [(None, 50)]             0         
 )                                                               
                                                                 
 tf_bert_model (TFBertModel)  TFBaseModelOutputWithPoo  108310272
                             lingAndCrossAttentions(l            
                             ast_hidden_state=(None,             
                             50, 768),                           
                              pooler_output=(None, 76            
                             8),                                 
                              past_key_values=None, h            
                             idden_states=None, atten            
                             tions=None, cross_attent            
                             ions=None)                    

In [56]:
b_model1 = create_bert_cls_model1()
history_wan1 = b_model1.fit(bert_train_input_ids,
                            bert_train_labels,
                            validation_data=(bert_val_input_ids,bert_val_labels),
                            batch_size=8,
                            epochs=2
                            )

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_ids_layer (InputLayer  [(None, 50)]             0         
 )                                                               
                                                                 
 tf_bert_model (TFBertModel)  TFBaseModelOutputWithPoo  108310272
                             lingAndCrossAttentions(l            
                             ast_hidden_state=(None,             
                             50, 768),                           
                              pooler_output=(None, 76            
                             8),                                 
                              past_key_values=None, h            
                             idden_states=None, atten            
                             tions=None, cross_attent            
                             ions=None)                    

6260/6260 [==============================] - 814s 128ms/step - loss: 0.0112 - accuracy: 0.9990 - val_loss: 0.0056 - val_accuracy: 0.9994
Epoch 2/2
6260/6260 [==============================] - 807s 129ms/step - loss: 0.0090 - accuracy: 0.9991 - val_loss: 0.0061 - val_accuracy: 0.9994


In [57]:
conf_matrix(b_model1,bert_val_input_ids,bert_val_labels)

Recall: 99.93664871713652
F1 Score: 99.96831432192648


(99.93664871713652, 99.96831432192648, array([[6310,    0],
        [   4,    0]]))

In [58]:
def create_bert_classification_model(bert_model,
                                     train_layers=-1,
                                     hidden_size = 200, 
                                     dropout=0.3,
                                     learning_rate=0.001):
    """
    Build a simple classification model with BERT. Use the Pooled Output for classification purposes
    """
    if train_layers == -1:
        # Freeze all layers of pre-trained BERT model
        bert_model.trainable = False

    else:
        # Restrict training to the train_layers outer transformer layers
        retrain_layers = []

        for retrain_layer_number in range(train_layers):

            layer_code = '_' + str(11 - retrain_layer_number)
            retrain_layers.append(layer_code)
          
        
        print('retrain layers: ', retrain_layers)

        for w in bert_model.weights:
            if not any([x in w.name for x in retrain_layers]):
                print('freezing: ', w)
                w._trainable = False

    input_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='input_ids_layer')
    token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='token_type_ids_layer')
    attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='attention_mask_layer')

    bert_inputs = {'input_ids': input_ids,
                   'token_type_ids': token_type_ids,
                   'attention_mask': attention_mask}      

    bert_out = bert_model(bert_inputs)

    pooled_token = bert_out[1]
    #cls_token = bert_out[0][:, 0, :]

    hidden = tf.keras.layers.Dense(hidden_size, activation='relu', name='hidden_layer')(pooled_token)


    hidden = tf.keras.layers.Dropout(dropout)(hidden)  


    classification = tf.keras.layers.Dense(1, activation='sigmoid',name='classification_layer')(hidden)
    
    classification_model = tf.keras.Model(inputs=[input_ids, token_type_ids, attention_mask], outputs=[classification])
    
    classification_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                                 loss=tf.keras.losses.BinaryCrossentropy(from_logits=False), 
                                 metrics='accuracy')
    
    return classification_model

In [59]:
bert_classification_model = create_bert_classification_model(bert_model, train_layers=-1)

In [60]:
bert_classification_model.summary()

Model: "model_6"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 attention_mask_layer (InputLay  [(None, 50)]        0           []                               
 er)                                                                                              
                                                                                                  
 input_ids_layer (InputLayer)   [(None, 50)]         0           []                               
                                                                                                  
 token_type_ids_layer (InputLay  [(None, 50)]        0           []                               
 er)                                                                                              
                                                                                            

In [61]:
xtrain_id=np.array(x_train.input_ids)
xtrain_token=np.array(x_train.token_type_ids)
xtrain_attn=np.array(x_train.attention_mask)
y_train=np.array(y_train)
xtest_id=np.array(x_test.input_ids)
xtest_token=np.array(x_test.token_type_ids)
xtest_attn=np.array(x_test.attention_mask)
y_test=np.array(y_test)

In [62]:
bert_classification_model_history = bert_classification_model.fit(
    [xtrain_id, xtrain_token, xtrain_attn],
    y_train,
    validation_data=([xtest_id, xtest_token, xtest_attn], y_test),
    batch_size=32,
    epochs=2
)  

Epoch 1/2
2000/2000 [==============================] - 284s 137ms/step - loss: 0.2658 - accuracy: 0.9298 - val_loss: 0.2515 - val_accuracy: 0.9308
Epoch 2/2
2000/2000 [==============================] - 271s 135ms/step - loss: 0.2614 - accuracy: 0.9301 - val_loss: 0.2556 - val_accuracy: 0.9308


In [63]:
conf_matrix(bert_classification_model,[xtest_id, xtest_token, xtest_attn],y_test)

Recall: 93.08490684006503
F1 Score: 96.41862573667508


(93.08490684006503, 96.41862573667508, array([[7444,    0],
        [ 553,    0]]))

In [64]:
def create_bert_train(bert_model,
                                     train_layers=1,
                                     hidden_size = 200, 
                                     dropout=0.3,
                                     learning_rate=0.001):
    """
    Build a simple classification model with BERT. Use the Pooled Output for classification purposes
    """
    if train_layers == -1:
        # Freeze all layers of pre-trained BERT model
        bert_model.trainable = False

    else:
        # Restrict training to the train_layers outer transformer layers
        retrain_layers = []

        for retrain_layer_number in range(train_layers):

            layer_code = '_' + str(11 - retrain_layer_number)
            retrain_layers.append(layer_code)
          
        
        print('retrain layers: ', retrain_layers)

        for w in bert_model.weights:
            if not any([x in w.name for x in retrain_layers]):
                print('freezing: ', w)
                w._trainable = False

    input_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='input_ids_layer')
    token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='token_type_ids_layer')
    attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='attention_mask_layer')

    bert_inputs = {'input_ids': input_ids,
                   'token_type_ids': token_type_ids,
                   'attention_mask': attention_mask}      

    bert_out = bert_model(bert_inputs)

    pooled_token = bert_out[1]
    #cls_token = bert_out[0][:, 0, :]

    hidden = tf.keras.layers.Dense(hidden_size, activation='relu', name='hidden_layer')(pooled_token)


    hidden = tf.keras.layers.Dropout(dropout)(hidden)  


    classification = tf.keras.layers.Dense(1, activation='sigmoid',name='classification_layer')(hidden)
    
    classification_model = tf.keras.Model(inputs=[input_ids, token_type_ids, attention_mask], outputs=[classification])
    
    classification_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                                 loss=tf.keras.losses.BinaryCrossentropy(from_logits=False), 
                                 metrics='accuracy')
    
    return classification_model

In [65]:
bert_classification_model_1 = create_bert_train(bert_model, train_layers=1)

Streaming output truncated to the last 5000 lines.
       -1.51268002e-02,  4.09861133e-02,  1.79283097e-02, -5.35483472e-03,
       -2.98706978e-03, -4.11610166e-03,  8.23723339e-03, -6.76035741e-03,
       -1.18157193e-02, -1.30932257e-02,  3.90395802e-03,  3.64464126e-03,
        1.26287220e-02,  2.92423018e-03,  2.90052244e-03,  1.54830581e-02,
       -1.53388758e-03, -1.32274730e-02,  1.29363837e-03, -3.10333334e-02,
        1.70161407e-02, -5.02192089e-03,  1.23756640e-02,  8.23881291e-03,
       -1.12304557e-02,  1.74133759e-02,  7.75301969e-03,  9.97138768e-03,
       -1.51928300e-02, -1.52893476e-02,  9.48150828e-03,  4.57647024e-03,
       -4.67498228e-03, -4.65134680e-02,  1.99273657e-02,  1.76182464e-02,
        4.86217998e-03,  2.99367998e-02, -1.52088637e-02, -1.49521269e-02,
       -8.50082841e-03,  2.31044041e-03, -1.08367959e-02, -2.70264735e-03,
        1.43175405e-02,  1.64633784e-02, -5.00891684e-03, -3.32544632e-02,
       -2.77614426e-02,  1.14871887e-03,  7.66586

In [66]:
bert_classification_model_history1 = bert_classification_model_1.fit(
    [xtrain_id, xtrain_token, xtrain_attn],
    y_train,
    validation_data=([xtest_id, xtest_token, xtest_attn], y_test),
    batch_size=32,
    epochs=2
)  

Epoch 1/2
2000/2000 [==============================] - 279s 137ms/step - loss: 0.2659 - accuracy: 0.9297 - val_loss: 0.2632 - val_accuracy: 0.9308
Epoch 2/2
2000/2000 [==============================] - 271s 135ms/step - loss: 0.2620 - accuracy: 0.9301 - val_loss: 0.2546 - val_accuracy: 0.9308


In [67]:
conf_matrix(bert_classification_model,[xtest_id, xtest_token, xtest_attn],y_test)

Recall: 93.08490684006503
F1 Score: 96.41862573667508


(93.08490684006503, 96.41862573667508, array([[7444,    0],
        [ 553,    0]]))

In [68]:
def create_bert_avg_model(hidden_size = 100, 
                                dropout=0.3,
                                learning_rate=0.00005):
    """
    Build a simple classification model with BERT. Use the average of the BERT output tokens
    """

    ### YOUR CODE HERE
    ### YOUR CODE HERE
    input_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='input_ids_layer')
    #token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='token_type_ids_layer')
    #attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='attention_mask_layer')

    
    bert_inputs = {'input_ids': input_ids}  

 

    bert_out = bert_model(bert_inputs)


    pooled_token = bert_out[0][:, 1:-1, :]
    #cls_token = bert_out[0][:, 0, :]
    bert_average=tf.math.reduce_mean(pooled_token,axis=1)

    #bert_average= tf.keras.layers.Reshape((bert_average.shape[-1],))

    hidden = tf.keras.layers.Dense(hidden_size, activation='relu', name='hidden_layer')(bert_average)


    hidden = tf.keras.layers.Dropout(dropout)(hidden)  

    classification = tf.keras.layers.Dense(1, activation='sigmoid',name='classification_layer')(hidden)
    
    classification_model = tf.keras.Model(inputs=[input_ids], outputs=[classification])
    
    classification_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                                 loss=tf.keras.losses.BinaryCrossentropy(from_logits=False), 
                                 metrics='accuracy')


    ### END YOUR CODE
    print(classification_model.summary())
    return classification_model


In [69]:
b_model1 = create_bert_avg_model()
history_wan = b_model1.fit(bert_train_input_ids,
                            bert_train_labels,
                            validation_data=(bert_test_input_ids,bert_test_labels),
                            batch_size=8,
                            epochs=2
                            )

Model: "model_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_ids_layer (InputLayer  [(None, 50)]             0         
 )                                                               
                                                                 
 tf_bert_model (TFBertModel)  TFBaseModelOutputWithPoo  108310272
                             lingAndCrossAttentions(l            
                             ast_hidden_state=(None,             
                             50, 768),                           
                              pooler_output=(None, 76            
                             8),                                 
                              past_key_values=None, h            
                             idden_states=None, atten            
                             tions=None, cross_attent            
                             ions=None)                    

In [70]:
conf_matrix(b_model1,bert_test_input_ids,bert_test_labels)

Recall: 99.95159728944822
F1 Score: 99.97579278625031


(99.95159728944822, 99.97579278625031, array([[6195,    0],
        [   3,    0]]))

In [71]:
def create_bert_cnn_model(hidden_size = 100, 
                                learning_rate=0.00005,
                                num_filters = [100, 100, 50, 25],
                                kernel_sizes = [3, 5, 10, 20],
                                dropout = 0.3):
    """
    Build a  classification model with BERT, where you apply CNN layers  to the BERT output
    """

    ### YOUR CODE HERE

    input_ids = tf.keras.layers.Input(shape=(50,), dtype=tf.int64, name='input_ids_layer')
    #token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='token_type_ids_layer')
    #attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int64, name='attention_mask_layer')

    bert_inputs = {'input_ids': input_ids}  

    bert_out = bert_model(bert_inputs)
 


    #pooled_token = bert_out[1]
    #pooled_token = bert_out[0]
    #cls_token = bert_out[0][:, 0, :]
  #bert_average=tf.math.reduce_mean(pooled_token,axis=1)


    conv_layers_for_all_kernel_sizes = []
    for kernel_size, filters in zip(kernel_sizes, num_filters):
        conv_layer = keras.layers.Conv1D(filters=filters, kernel_size=kernel_size, activation='relu')(bert_out[0])
        conv_layer = keras.layers.GlobalMaxPooling1D()(conv_layer)
        conv_layers_for_all_kernel_sizes.append(conv_layer)
    
    conv_output = keras.layers.concatenate(conv_layers_for_all_kernel_sizes, axis=1)
    #last_hidden_output = keras.layers.Dropout(rate=dropout)(conv_output)

    
    last_hidden_output = keras.layers.Dense(hidden_size, activation='relu')(conv_output)
    last_hidden_output = keras.layers.Dropout(dropout)(last_hidden_output)

    #flatt=keras.layers.Flatten()(last_hidden_output)
    #cnn_prediction = keras.layers.Dense(1, activation='sigmoid')(last_hidden_output)
    cnn_prediction = keras.layers.Dense(1, activation='sigmoid')(last_hidden_output)

    classification_model = keras.Model(inputs=input_ids, outputs=cnn_prediction)
    classification_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                      loss='binary_crossentropy',  # From information theory notebooks.
                      metrics=['accuracy'])
   
    ### END YOUR CODE
    
    print(classification_model.summary())
    return classification_model

In [72]:
cnn_bert_model=create_bert_cnn_model()
cnn_bert_model.summary

Model: "model_9"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids_layer (InputLayer)   [(None, 50)]         0           []                               
                                                                                                  
 tf_bert_model (TFBertModel)    TFBaseModelOutputWi  108310272   ['input_ids_layer[0][0]']        
                                thPoolingAndCrossAt                                               
                                tentions(last_hidde                                               
                                n_state=(None, 50,                                                
                                768),                                                             
                                 pooler_output=(Non                                         

<bound method Model.summary of <keras.engine.functional.Functional object at 0x7faa8050c040>>

In [73]:
cnn_bert_history = cnn_bert_model.fit(bert_train_input_ids,
                            bert_train_labels,
                            validation_data=(bert_test_input_ids,bert_test_labels),
                            batch_size=8,
                            epochs=2
                            )

Epoch 1/2
6260/6260 [==============================] - 365s 57ms/step - loss: 0.0086 - accuracy: 0.9991 - val_loss: 0.0042 - val_accuracy: 0.9995
Epoch 2/2
6260/6260 [==============================] - 349s 56ms/step - loss: 0.0085 - accuracy: 0.9991 - val_loss: 0.0043 - val_accuracy: 0.9995


In [74]:
conf_matrix(cnn_bert_model,bert_test_input_ids,bert_test_labels)

Recall: 99.95159728944822
F1 Score: 99.97579278625031


(99.95159728944822, 99.97579278625031, array([[6195,    0],
        [   3,    0]]))